[versions]
firebaseMessaging = "24.0.2"
me = "1.0.0-rc2-SNAPSHOT"
podFirebase = "11.3.0"
kotlin = "2.0.21-RC"
compose = "1.7.0-beta02"
agp = "8.7.0"
androidx-activityCompose = "1.9.2"
androidx-uiTest = "1.7.3"
maven-publish = "0.29.0"
google-services = "4.4.2"
firebaseCommonKtx = "21.0.0"
[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }

[plugins]
native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }