# Uncomment the next line to define a global platform for your project
platform :ios, '13'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'FirebaseCore' , '11.3.0'
  pod "FirebaseMessaging" , "11.3.0"
  pod "FirebaseAnalytics" , '11.3.0'
  pod "FirebaseCrashlytics" , '11.3.0'
  pod "FirebaseAuth" , '11.3.0'
  pod 'kfirebaseFirestore' , '0.1.0-7-rc'
  pod 'FirebaseDatabase', '11.3.0'
  pod "FirebaseStorage" , "11.3.0"


end
