# Uncomment the next line to define a global platform for your project
platform :ios, '13'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'FirebaseCore' , '11.3.0' 
  pod "KFirebaseMessaging" , "0.1.0-beta.6"
end
